name = "FluxMLBenchmarks"
uuid = "6680a82f-826c-4bff-bf11-7163c7cf257a"
authors = ["Kyle Daruwalla <daruwalla@wisc.edu> and contributors"]
version = "1.0.0-DEV"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
BenchmarkCI = "20533458-34a3-403d-a444-e18f38190b5b"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PkgBenchmark = "32113eaa-f34f-5b0d-bd6c-c81e245fc73d"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
URIParser = "30578b45-9adc-5946-b283-645ec420af67"

[compat]
ArgParse = "1"
BenchmarkCI = "0.1"
BenchmarkTools = "1"
PkgBenchmark = "0.2"
URIParser = "0.4"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
